Enable users to discover how to update the python-build plugin

diff --git a/plugins/python-build/bin/pyenv-install b/plugins/python-build/bin/pyenv-install
--- a/plugins/python-build/bin/pyenv-install
+++ b/plugins/python-build/bin/pyenv-install
@@ -24,6 +24,10 @@
 # python-build, including a list of environment variables for adjusting
 # compilation, see: https://github.com/pyenv/pyenv#readme
 #
+# If the version you are looking for is missing, you probably need to update
+# your pyenv python-build plugin. For information on how to do so, run:
+#   pyenv install how-do-i-update-my-pyenv-build-plugin
+#
 set -e
 [ -n "$PYENV_DEBUG" ] && set -x
 
@@ -82,6 +86,10 @@ for option in "${OPTIONS[@]}"; do
   "l" | "list" )
     echo "Available versions:"
     definitions | indent
+    {
+      echo "Can't find the version you want? Run:"
+      echo "pyenv install how-do-i-update-my-pyenv-build-plugin"
+    } >&2
     exit
     ;;
   "f" | "force" )
