python-build: install_git: Support verifying the checkout by SHA-1 (#3586)
* For annotated tags, support matching both tag SHA and peeled commit SHA

diff --git a/plugins/python-build/bin/python-build b/plugins/python-build/bin/python-build
--- a/plugins/python-build/bin/python-build
+++ b/plugins/python-build/bin/python-build
@@ -681,6 +681,18 @@ fetch_git() {
   local package_name="$1"
   local git_url="$2"
   local git_ref="$3"
+  local git_sha=
+  
+  # Checking the ref's SHA-1 is enough to ensure its authenticity according to Linus Torvalds
+  # https://security.stackexchange.com/questions/67920/how-safe-are-signed-git-tags-only-as-safe-as-sha-1-or-somehow-safer
+  # ":" is illegal in ref names, see git-check-ref-format(1) manpage
+  # https://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name
+  # So we can use it as a delimiter
+  if [[ $git_ref =~ :(.*)$ ]]; then
+    git_sha="${BASH_REMATCH[1]}"
+    # Bash 3.2/Busybox don't support negative length in substring expansion
+    git_ref="${git_ref::${#git_ref}-${#BASH_REMATCH[0]}}"
+  fi
 
   echo "Cloning ${git_url}..." >&2
 
@@ -710,6 +722,25 @@ fetch_git() {
   else
     echo "error: please install \`git\` and try again" >&2
     exit 1
+  fi
+  
+  if [[ -n $git_sha ]]; then
+    #If the tag is annotated, its underlying ("peeled") commit is checked out instead
+    #In this case, we accept either commit's SHA or tag's SHA for convenience
+    (
+      declare tag_sha commit_sha
+      cd "${package_name}";
+      if git describe --exact-match 2>/dev/null | grep -xF "$git_ref" >/dev/null;then
+        tag_sha=$(git rev-parse "$git_ref")
+      fi
+      commit_sha=$(git rev-parse HEAD)
+      if [[ (-z $tag_sha || $git_sha != "$tag_sha") && $git_sha != "$commit_sha" ]]; then
+        echo -n "error: ref \`${git_ref}' SHA-1 mismatch: expected $git_sha, got $commit_sha" >&2
+        if [[ -n $tag_sha ]]; then echo -n "(commit) and $tag_sha(tag)" >&2; fi
+        echo >&2
+        exit 1
+      fi
+    )
   fi
 }
 
