Use lock file in writable directory and update tests

diff --git a/libexec/pyenv-rehash b/libexec/pyenv-rehash
--- a/libexec/pyenv-rehash
+++ b/libexec/pyenv-rehash
@@ -6,11 +6,16 @@ set -e
 
 SHIM_PATH="${PYENV_ROOT}/shims"
 PROTOTYPE_SHIM_PATH="${SHIM_PATH}/.pyenv-shim"
-LOCK_FILE_PATH=/var/lock/pyenv
+LOCK_FILE_PATH="${SHIM_PATH}/.pyenv.lock"
 LOCK_FILE_FD=90
 
 # Create the shims directory if it doesn't already exist.
 mkdir -p "$SHIM_PATH"
+
+if ! [ -w "$SHIM_PATH" ]; then
+  echo "pyenv: cannot rehash: $SHIM_PATH isn't writable"
+  exit 1
+fi
 
 # Ensure only one instance of pyenv-rehash is running at a time.
 if command -v flock &>/dev/null; then
@@ -31,12 +36,10 @@ else
   set -o noclobber
   { echo > "$PROTOTYPE_SHIM_PATH"
   } 2>/dev/null ||
-  { if [ -w "$SHIM_PATH" ]; then
+  { if [ -e "$SHIM_PATH" ]; then
       echo "pyenv: cannot rehash: $PROTOTYPE_SHIM_PATH exists"
-    else
-      echo "pyenv: cannot rehash: $SHIM_PATH isn't writable"
+      exit 1
     fi
-    exit 1
   } >&2
   set +o noclobber
 fi
@@ -51,6 +54,7 @@ release_lock() {
 
   if command -v flock &>/dev/null; then
     flock --unlock $LOCK_FILE_FD
+    rm -f $LOCK_FILE_PATH
   elif command -v shlock &>/dev/null; then
     rm -f $LOCK_FILE_PATH
   fi
