Add defensive check for unset PYENV_ROOT in init_dirs

diff --git a/libexec/pyenv-init b/libexec/pyenv-init
--- a/libexec/pyenv-init
+++ b/libexec/pyenv-init
@@ -169,6 +169,11 @@ function help_() {
 }
 
 function init_dirs() {
+  if [ -z "$PYENV_ROOT" ]; then
+    echo 'Error: PYENV_ROOT is not set. Aborting.' >&2
+    exit 1
+  fi
+
   mkdir -p "${PYENV_ROOT}/"{shims,versions}
 }
 
