Import recent changes from rbenv 0.4.0

diff --git a/libexec/pyenv b/libexec/pyenv
--- a/libexec/pyenv
+++ b/libexec/pyenv
@@ -1,9 +1,25 @@
 #!/usr/bin/env bash
 set -e
-[ -n "$PYENV_DEBUG" ] && set -x
+export -n CDPATH
+
+if [ "$1" = "--debug" ]; then
+  export PYENV_DEBUG=1
+  shift
+fi
+
+if [ -n "$PYENV_DEBUG" ]; then
+  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
+  set -x
+fi
+
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "pyenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
 
 resolve_link() {
-  $(type -p greadlink readlink | head -1) "$1"
+  $READLINK "$1"
 }
 
 abs_dirname() {
diff --git a/libexec/pyenv-hooks b/libexec/pyenv-hooks
--- a/libexec/pyenv-hooks
+++ b/libexec/pyenv-hooks
@@ -19,13 +19,18 @@ if [ -z "$PYENV_COMMAND" ]; then
   exit 1
 fi
 
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "pyenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
+
 resolve_link() {
-  $(type -p greadlink readlink | head -1) $1
+  $READLINK "$1"
 }
 
 realpath() {
   local cwd="$(pwd)"
-  local base="$(basename $1)"
   local path="$1"
 
   while [ -n "$path" ]; do
@@ -34,13 +39,15 @@ realpath() {
     path="$(resolve_link "$name" || true)"
   done
 
-  echo "$(pwd)/$base"
+  echo "$(pwd)/$name"
   cd "$cwd"
 }
 
+IFS=: hook_paths=($PYENV_HOOK_PATH)
+
 shopt -s nullglob
-for path in ${PYENV_HOOK_PATH//:/$'\n'}; do
-  for script in $path/"$PYENV_COMMAND"/*.bash; do
+for path in "${hook_paths[@]}"; do
+  for script in "$path/$PYENV_COMMAND"/*.bash; do
     echo $(realpath $script)
   done
 done
