Make pyenv-rehash safer for multiple processes

diff --git a/libexec/pyenv-rehash b/libexec/pyenv-rehash
--- a/libexec/pyenv-rehash
+++ b/libexec/pyenv-rehash
@@ -6,9 +6,43 @@ set -e
 
 SHIM_PATH="${PYENV_ROOT}/shims"
 PROTOTYPE_SHIM_PATH="${SHIM_PATH}/.pyenv-shim"
+LOCK_FILE_PATH=/var/lock/pyenv
+LOCK_FILE_FD=90
 
 # Create the shims directory if it doesn't already exist.
 mkdir -p "$SHIM_PATH"
+
+wait_for_lock() {
+  # flock(1) exists on Linux with util-linux and is the most reliable
+  if command -v flock &>/dev/null; then
+    eval "exec $LOCK_FILE_FD>\"$LOCK_FILE_PATH\""
+    flock --exclusive $LOCK_FILE_FD
+  # Fall back to shlock on BSD systems
+  elif command -v shlock &>/dev/null; then
+    # Try forever to acquire the lock
+    while ! shlock -f "$LOCK_FILE_PATH" -p $$; do
+      sleep 0.5
+    done
+  else
+    echo 'pyenv: cannot rehash: $PYENV_REHASH_PARALLEL_SAFE is set, but this system does not have flock or shlock.' >&2
+    exit 1
+  fi
+}
+
+release_lock() {
+  if command -v flock &>/dev/null; then
+    flock --unlock $LOCK_FILE_FD
+  elif command -v shlock &>/dev/null; then
+    rm -f $LOCK_FILE_PATH
+  fi
+}
+
+# When the PYENV_REHASH_PARALLEL_SAFE variable is set and flock(1) or shlock(1)
+# is available, this script can acquire an exclusive file lock to ensure only
+# one process is running pyenv-rehash.
+if [ -n "$PYENV_REHASH_PARALLEL_SAFE" ]; then
+  wait_for_lock
+fi
 
 # Ensure only one instance of pyenv-rehash is running at a time by
 # setting the shell's `noclobber` option and attempting to write to
@@ -32,6 +66,9 @@ trap remove_prototype_shim EXIT
 
 remove_prototype_shim() {
   rm -f "$PROTOTYPE_SHIM_PATH"
+  if [ -n "$PYENV_REHASH_PARALLEL_SAFE" ]; then
+    release_lock
+  fi
 }
 
 # The prototype shim file is a script that re-execs itself, passing
