Fail hard if RBENV_NATIVE_EXT is set but extensions failed to load

diff --git a/libexec/rbenv b/libexec/rbenv
--- a/libexec/rbenv
+++ b/libexec/rbenv
@@ -18,6 +18,10 @@ if enable -f "${0%/*}"/../libexec/rbenv-realpath.dylib realpath 2>/dev/null; the
     echo "${path%/*}"
   }
 else
+  if [ -n "$RBENV_NATIVE_EXT" ]; then
+    echo "rbenv: failed to load \`realpath' builtin" >&2
+    exit 1
+  fi
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
   echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
diff --git a/libexec/rbenv-hooks b/libexec/rbenv-hooks
--- a/libexec/rbenv-hooks
+++ b/libexec/rbenv-hooks
@@ -20,6 +20,10 @@ if [ -z "$RBENV_COMMAND" ]; then
 fi
 
 if ! enable -f "${BASH_SOURCE%/*}"/rbenv-realpath.dylib realpath 2>/dev/null; then
+  if [ -n "$RBENV_NATIVE_EXT" ]; then
+    echo "rbenv: failed to load \`realpath' builtin" >&2
+    exit 1
+  fi
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
   echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
