better error message for `rbenv prefix system`
Have `rbenv prefix` handle the case where system Ruby is not installed,
i.e. `rbenv which ruby` doesn't find ruby in PATH.

Fixes #362

diff --git a/libexec/rbenv-prefix b/libexec/rbenv-prefix
--- a/libexec/rbenv-prefix
+++ b/libexec/rbenv-prefix
@@ -22,10 +22,14 @@ elif [ -z "$RBENV_VERSION" ]; then
 fi
 
 if [ "$RBENV_VERSION" = "system" ]; then
-  RUBY_PATH="$(rbenv-which ruby)"
-  RUBY_PATH="${RUBY_PATH%/*}"
-  echo "${RUBY_PATH%/bin}"
-  exit
+  if RUBY_PATH="$(rbenv-which ruby 2>/dev/null)"; then
+    RUBY_PATH="${RUBY_PATH%/*}"
+    echo "${RUBY_PATH%/bin}"
+    exit
+  else
+    echo "rbenv: system version not found in PATH" >&2
+    exit 1
+  fi
 fi
 
 RBENV_PREFIX_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}"
