indentation

diff --git a/libexec/rbenv b/libexec/rbenv
--- a/libexec/rbenv
+++ b/libexec/rbenv
@@ -28,26 +28,26 @@ if enable -f "${BASH_SOURCE%/*}"/../libexec/rbenv-realpath.dylib realpath 2>/dev
 else
   [ -z "$RBENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"
 
-READLINK=$(type -p greadlink readlink | head -1)
-[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
+  READLINK=$(type -p greadlink readlink | head -1)
+  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
 
-resolve_link() {
-  $READLINK "$1"
-}
+  resolve_link() {
+    $READLINK "$1"
+  }
 
-abs_dirname() {
-  local cwd="$(pwd)"
-  local path="$1"
+  abs_dirname() {
+    local cwd="$(pwd)"
+    local path="$1"
 
-  while [ -n "$path" ]; do
-    cd "${path%/*}"
-    local name="${path##*/}"
-    path="$(resolve_link "$name" || true)"
-  done
+    while [ -n "$path" ]; do
+      cd "${path%/*}"
+      local name="${path##*/}"
+      path="$(resolve_link "$name" || true)"
+    done
 
-  pwd
-  cd "$cwd"
-}
+    pwd
+    cd "$cwd"
+  }
 fi
 
 if [ -z "${RBENV_ROOT}" ]; then
