Silence errors when piping `type | head -1`

diff --git a/libexec/rbenv-help b/libexec/rbenv-help
--- a/libexec/rbenv-help
+++ b/libexec/rbenv-help
@@ -42,13 +42,15 @@ extract_initial_comment_block() {
 }
 
 collect_documentation() {
-  local all_awks
-  local first_awk
-  all_awks=$(type -p gawk awk)
-  first_awk=$(head -1 <<<"$all_awks")
+  local awk
+  awk="$(type -p gawk awk 2>/dev/null | head -1)"
+  if [ -z "$awk" ]; then
+    echo "rbenv: cannot find awk" >&2
+    return 1
+  fi
 
   # shellcheck disable=SC2016
-  "$first_awk" '
+  "$awk" '
     /^Summary:/ {
       summary = substr($0, 10)
       next
