bail out early if readlink is not available
readlink comes from GNU coreutils.  On systems without it, rbenv used to
spin out of control when it didn't have readlink or greadlink available
because it would re-exec the frontend script over and over instead of the
worker script in libexec.

Fixes #389

diff --git a/libexec/rbenv b/libexec/rbenv
--- a/libexec/rbenv
+++ b/libexec/rbenv
@@ -12,8 +12,14 @@ if [ -n "$RBENV_DEBUG" ]; then
   set -x
 fi
 
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
+
 resolve_link() {
-  $(type -p greadlink readlink | head -1) "$1"
+  $READLINK "$1"
 }
 
 abs_dirname() {
